#!/usr/bin/env python3('')
all = open('ferret_all_genes.tsv','r')
stem = open('ferret_stemcellproliferation_genes.tsv','r')
pig = open('ferret_pigmentation_genes.tsv','r')
trans = open('ferret_transcriptionFactors.tsv','r')
set_all = set(all)
set_stem = set(stem)
set_pig = set(pig)
set_trans = set(trans)
set_pigs = set_pig.discard('Gene stable ID\n')
not_stem = set_all - set_stem
#print(not_stem)
all_stem = set(set_all & set_stem)
all_pig = set(set_all & set_pig)
stem_pig = set(all_stem & all_pig)
stem_trans = set(set_trans & set_stem)
print(stem_pig)
print(stem_trans)